### PR TITLE
adding decompression of gzipped files

### PR DESCRIPTION
**Pull request by kkdd**

### CODE REVIEW

**Comment by leplatrem** [comment]
Nice :) 

I think that this is a little bit out of scope for this tiny tool though.

We should use this use-case to introduce the necessary «hooks» to allow to support decompression, as you did, but not merge it with the plugin code.

What do you think ?

**Comment by kkdd** [comment]
Thank you for your idea.
Would it be better by separating the following function code from leaflet.filelayer.js?

```
 /*
  * Requires ukyo's jsziptools.js to be in global scope when decompressing gzipped files
  * https://github.com/ukyo/jsziptools
  * http://ukyo.github.io/jsziptools/jsziptools.js
  */

this._decompressors = {
    gz: function (x) {return gzip.decompress(x);}
};

var gzip = (function () {
    return {
        decompress: function(arrayBuffer) {
            var hexarr = jz.gz.decompress(arrayBuffer);
            return _hextostring(hexarr);
        },
    };
    function _hextostring(hexarr){
        for (var w = '', i = 0, l = hexarr.length; i < l; i++) {
            w += String.fromCharCode(hexarr[i])
        }
        return decodeURIComponent(escape(w));
    }
})();
```

**Comment by leplatrem** [comment]
We could add an API to add custom parsers. For example:

```js
gzipParser = {
  extensions: ['.gzip'],
  read: function (fileReader) {
    return fileReader.readAsArrayBuffer()
  },
  toGeoJSONString: function(data) {
    // ... your custom gzip code
  }
}     

L.FileLayer.FileLoader.addParser(gzipParser);
```

It would require some refactor here and there, but I think it would be beneficial for the existing code too.

What do you think?

**Comment by nathanvda** [comment]
Very much in favour of an API to add custom parsers. I would want to add shp/xml/csv parsers but for the moment these all reside in separate plugins with overlapping functionality. 

Do you need any help to add that?

**Comment by leplatrem** [comment]
> Do you need any help to add that?

I don't contribute to this library anymore. But would be glad to review/test if someone submits some code :)

**Comment by kkdd** [comment]
New PR: https://github.com/makinacorpus/Leaflet.FileLayer/pull/56

**Pull request closed without merging**
