### PR TITLE
Allow to select multiple files in the file dialog

### PR DESCRIPTION
**Pull request by jens-duttke**
Extend the file dialog by the possibility to select multiple files at once.

### CODE REVIEW

**Comment by leplatrem** [comment]
Hi Jens,
Could take a look at the tests ?
Thanks !

**Comment by jens-duttke** [comment]
Hello leplatrem,

in August I tried to install all npm packages using "npm install", after 3 hours I aborted the installation process. In that time npm created an endless structure of folders, which I wasn't able to delete with Windows tools, I had to download a special tool which was able to get rid of all the files.
I think there was a circular reference in the mocha package, or maybe a bug in npm.

Whatever, I've tried it again now, and it downloaded the packages in less than 10 seconds without problems.

But now I have the next problem, I'm not sure how to great an automatic unit test for that.
How would you test the opening of multiple files especially using drag&drop? To me it looks like there are no unittests for that, which I could use as base for my tests.

**Comment by leplatrem** [comment]
Hi,

Thanks for coming back  :) Sorry for the delay, I don't work for the company anymore :|

Indeed, there might not be too much tests already there. Maybe you could just add a small test to check that the input field has the 'multiple' option. 
It would be a symbolic test, but at least it proves that our intentions are to test the changes of this PR :)

**Comment by fredericbonifas** [comment]
Thanks for the PR @jens-duttke !

I merged your PR, adding a test to assert that the input has the 'multiple' option

**Pull request merged**
